# Generated by Django 4.2.19 on 2025-02-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='content',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='article_url',
            field=models.URLField(default='https://www.researchgate.net/', help_text='News Article link'),
            preserve_default=False,
        ),
    ]
