# Generated by Django 4.2.19 on 2025-05-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_live', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('training', 'Live Training'), ('event', 'Live Event'), ('saved', 'Saved')], max_length=25)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=255, null=True)),
                ('zoom_join_url', models.URLField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
